/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HotelReservationSystem;

import org.junit.Test;
import static org.junit.Assert.*;

public class HotelReservationSystemTest {
	@Test
	public void addHotel_validInput_ListSizeIncreased() {
		HotelReservationSystem system = new HotelReservationSystem();
		int oldSize = system.getHotelList().size();
		system.addHotel("Hotel 1", 80);
		assertEquals(oldSize+1,system.getHotelList().size());
	}
}
